name: NLP Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract-people:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download pt_core_news_sm

      - name: Executar extração de pessoas
        run: |
          python extrair_pessoas.py "João da Silva e Maria Oliveira participaram da reunião com o ministro Carlos Souza."
